version: "3.7"


services:
  s3-fs:
    build:
      context: .
      target: development
      args:
        GOOS: linux
        GOARCH: amd64
    volumes:
      - ./:/app/
    env_file:
      - do.env
    ports:
      - "8088:8080"
      - "6060:6060"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
        reservations:
          memory: 512m