version: "3.7"


services:
  s3-fs:
    build:
      context: .
      target: production
      args:
        GOOS: linux
        GOARCH: amd64
    env_file:
      - do.env
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128m
        reservations:
          memory: 128m